### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/fsl/etc/fslversion'

### ISSUE THREAD

**Issue by Cynthia0629** [miykael/nipype_tutorial#11]
I am new with nipype .And when I'm trying to run the example code on "https://miykael.github.io/nipype_tutorial/notebooks/example_preprocessing.html" It come to an error when debug with this line"from nipype.interfaces.fsl import MCFLIRT, FLIRT" the error comes just as the title say:

Traceback (most recent call last):
  File "/home/cynthia/PycharmProjects/FSL_installation/note_book.py", line 4, in <module>
    from nipype.interfaces.fsl import MCFLIRT, FLIRT
  File "/home/cynthia/anaconda3/lib/python3.6/site-packages/nipype/interfaces/fsl/__init__.py", line 13, in <module>
    from .model import (Level1Design, FEAT, FEATModel, FILMGLS, FEATRegister,
  File "/home/cynthia/anaconda3/lib/python3.6/site-packages/nipype/interfaces/fsl/model.py", line 661, in <module>
    class FILMGLS(FSLCommand):
  File "/home/cynthia/anaconda3/lib/python3.6/site-packages/nipype/interfaces/fsl/model.py", line 694, in FILMGLS
    if Info.version() and LooseVersion(Info.version()) > LooseVersion('5.0.6'):
  File "/home/cynthia/anaconda3/lib/python3.6/site-packages/nipype/interfaces/fsl/base.py", line 77, in version
    out = open('%s/etc/fslversion' % (basedir)).read()
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/fsl/etc/fslversion'

Is there anyone who can tell me what I can do to fix this?

**Comment by miykael** [comment]
I'm very sorry for my incredibly late reply @Cynthia0629. The error seems to point to an issue with the FSL installation. Have you already been able to solve the issue in the mean time? Otherwise, I'm very happy to help you.
