### ISSUE TITLE
_check_mandatory_inputs error

### ISSUE THREAD

**Issue by tashrifbillah** [miykael/nipype_tutorial#147]
Hi @miykael , I am trying to go through your Tutorial but running into errors when trying to wrap a function as a Node. What I understand is, the wrapped function does not receive input from `select_files` node. My simple workflow is following:

![image](https://user-images.githubusercontent.com/35086881/68433289-279af900-0184-11ea-91bc-ed8e400d233e.png)

```
#!/usr/bin/env python

from nipype import Node, Function, Workflow, SelectFiles, IdentityInterface
from nipype.interfaces import DataSink

# input and output paths
output_base_dir= '/tmp/basic_pipeline_output'
input_base_directory= '/tmp/basic_pipeline_input'
data_sink_directory= '/tmp/basic_pipeline_datasink'
cases=['01','02', '03']


# funtion to wrap
def print_file_name(fileName):
    print(fileName)
    return fileName+'.hello'


infosource = Node(IdentityInterface(fields=['subject_id']), name="infosource")
infosource.iterables = [('subject_id', cases)]

templates = {'t1w': '{subject_id}.txt'}
select_files= Node(SelectFiles(templates, base_directory= input_base_directory), name= 'select_files')

print_name= Node(Function(input_names=['fileName'], output_names=['outFileName']), function= print_file_name, name= 'print_name')
data_sink = Node(DataSink(base_directory=output_base_dir), name='datasink')

basic_pipeline= Workflow(name='basic_pipeline', base_dir= data_sink_directory)

# does not work
basic_pipeline.connect([(infosource, select_files, [('subject_id','subject_id')]),
                        (select_files, print_name, [('t1w','fileName')]),
                        (print_name, data_sink, [('outFileName','copy')])
                        ])


# works
# basic_pipeline.connect([(infosource, select_files, [('subject_id','subject_id')]),
#                         (select_files, data_sink, [('t1w','copy')])
#                         ])


basic_pipeline.write_graph('basic_pipeline.dot', graph2use='flat')

basic_pipeline.run()
```
Error:

```
Traceback (most recent call last):
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 480, in run
    self._check_mandatory_inputs()
  File "/home/tb571/miniconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py", line 389, in _check_mandatory_inputs
    raise ValueError(msg)
ValueError: Function requires a value for input 'function_str'. For a list of required inputs, see Function.help()
```

To reproduce the error, please generate the files:
```
mkdir /tmp/basic_pipeline_input
touch /tmp/basic_pipeline_input/01.txt /tmp/basic_pipeline_input/02.txt /tmp/basic_pipeline_input/03.txt
```

Would you be able to help? It should be quick for an expert to answer.

**Comment by tashrifbillah** [comment]
The answer is here 
https://miykael.github.io/nipype_tutorial/notebooks/advanced_create_interfaces.html#Complete-approach---pure-Python-interface
